print("Hello Everyone")
print("Perkenalkan") 
print("Nama 		: Satrio Putra Agustin") 
print("NIM		: 202551125")
print("Jenis kelamin	: Laki-laki")
print("Angkatan	: 2025")
print("Fakultas	: Teknik")
print("Prodi		: Teknik Informatika")
print("Keles		: D")
print("Universitas	: Universitas Muria Kudus")
print("Alamat Rumah	: Jln Supriyadi No.24 Ds. Juwanalan Rt.10/ Rw.05 Kel. Pati Kidul Kec. Pati Kab. Pati")